INSERT INTO typology (id, name_typology) VALUES
("011", "Artisti lirici"),
("012", "Cantanti"),
("013", "Coristi e vocalisti"),
("014", "Maestri del coro, assistenti, aiuti (suggeritori del coro)"),
("021", "Attori di prosa (Mimi)"),
("022", "Attori cinematografici e di audiovisivi"),
("023", "Attori doppiatori"),
("024", "Attori di operetta"),
("025", "Artisti di rivista, varieta\" ed attrazioni (comici, fantasisti, soubrette)"),
("026", "Artisti del circo (acrobati, clown, domatori, fantasisti)"),
("027", "Attori di fotoromanzi"),
("028", "Suggeritori teatrali, cinematografici e di audiovisivi"),
("029", "Generici e figuranti speciali"),
("031", "Presentatori"),
("032", "Disc-jockey"),
("033", "Animatori in strutture ricettive connesse all\"attivita\" turistica"),
("041", "Registi teatrali, cinematografici e di audiovisivi"),
("042", "Aiuto registi teatrali, cinematografici e di audiovisivi"),
("043", "Sceneggiatori teatrali, cinematografici e di audiovisivi"),
("044", "Dialoghisti ed adattatori"),
("045", "Direttori della fotografia, light designer"),
("046", "Soggettisti"),
("047", "Video-assist"),
("051", "Direttori di produzione"),
("052", "Ispettori di produzione"),
("053", "Segretari di produzione"),
("054", "Segretari di edizione"),
("055", "Cassieri di produzione"),
("056", "Organizzatori generali, location manager"),
("057", "Responsabili di edizione della produzione cinematografica e televisiva"),
("058", "Casting director"),
("059", "Documentalisti audiovisivi"),
("061", "Direttori di scena"),
("062", "Direttori di doppiaggio"),
("063", "Assistenti di scena e di doppiaggio"),
("071", "Direttori d\"orchestra"),
("072", "Sostituti direttori d\"orchestra"),
("073", "Maestri suggeritori (maestri collaboratori)"),
("074", "Maestri di banda"),
("075", "Compositori"),
("081", "Concertisti e solisti"),
("082", "Professori d\"orchestra"),
("083", "Orchestrali anche di musica leggera"),
("084", "Bandisti"),
("085", "Consulenti assistenti musicali"),
("091", "Coreografi ed assistenti coreografi"),
("092", "Ballerini e tersicorei"),
("093", "Indossatori"),
("094", "Figuranti lirici"),
("095", "Figuranti di sala"),
("096", "Fotomodelli"),
("097", "Cubisti"),
("098", "Spogliarellisti"),
("101", "Amministratori di formazione artistica"),
("102", "Amministratori di produzione cinematografica e audiovisiva"),
("103", "Organizzatori teatrali"),
("104", "Amministratori e segretari di compagnie teatrali"),
("111", "Tecnici del montaggio e del suono della produzione cinematografica"),
("112", "Tecnici del montaggio e del suono del teatro"),
("113", "Tecnici del montaggio e del suono di audiovisivi"),
("114", "Tecnici del montaggio e del suono di altri settori dello spettacolo"),
("115", "Tecnici dello sviluppo e stampa, luci, scena ed altri tecnici della produzione cinematografica"),
("116", "Tecnici delle luci, scena ed altri tecnici del teatro"),
("117", "Tecnici delle luci, scena ed altri tecnici audiovisivi"),
("118", "Tecnici dello sviluppo e stampa, luci, scena ed altri tecnici di fotoromanzi"),
("119", "Tecnici addetti alle manifestazioni di moda"),
("121", "Operatori di ripresa cinematografica e audiovisiva"),
("122", "Aiuto operatori di ripresa cinematografica ed audiovisiva"),
("123", "Maestranze cinematografiche"),
("124", "Maestranze teatrali"),
("125", "Maestranze delle imprese audiovisivi"),
("126", "Fotografi di scena"),
("131", "Architetti, arredatori"),
("132", "Costumisti, figurinisti, modiste"),
("133", "Scenografi"),
("134", "Bozzettista"),
("135", "Story board artist"),
("136", "Creatori di fumetti, illustrazioni e disegni finalizzati all\"animazione"),
("141", "Truccatori"),
("142", "Parrucchieri"),
("154", "Artieri ippici"),
("155", "Operatori di cabina di sale cinematografiche"),
("156", "Maschere, custodi, guardarobieri, addetti alle pulizie e al facchinaggio"),
("157", "Maschere, custodi, guardarobieri, addetti alle pulizie e al facchinaggio dipendenti dagli enti ed imprese esercenti pubblici spettacoli"),
("158", "Maschere, custodi, guardarobieri, addetti alle pulizie e al facchinaggio dipendenti dalle imprese della produzione cinematografica, del doppiaggio e dello sviluppo e stampa"),
("201", "Impiegati amministrativi e tecnici dipendenti da imprese audiovisivi"),
("202", "Impiegati amministrativi e tecnici dipendenti da Enti ed imprese esercenti pubblici spettacolo (cassieri e Direttori di sala)");